### ISSUE TITLE
Uncaught TypeError: Cannot read property 'activeItem' of undefined

### ISSUE THREAD

**Issue by c10b10** [t9md/atom-paner#3]
[Enter steps to reproduce below:]
1. run shortcut for panner:very-right

**Atom Version**: 1.4.2
**System**: Mac OS X 10.11.2
**Thrown From**: [paner](https://github.com/t9md/atom-paner) package, v0.1.14
### Stack Trace

Uncaught TypeError: Cannot read property 'activeItem' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:54

TypeError: Cannot read property 'activeItem' of undefined
    at new Pane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:54:31)
    at Object.module.exports.moveToVery (/Users/c10b10/.atom/packages/paner/lib/main.coffee:163:19)
    at atom-workspace.subscriptions.add.atom.commands.add.paner:very-right (/Users/c10b10/.atom/packages/paner/lib/main.coffee:57:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:11 vim-mode:undo (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:10.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:10 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:09.6.0 ex-mode:open (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:09.6.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:09.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:09.3.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:08.0 ex-mode:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:08.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:07.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:07.7.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:06.3.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  6x -0:06.2.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:03.4.0 window:focus-pane-on-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:03.4.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:01.1.0 paner:very-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "tree-view",
      "nuclide"
    ],
    "themes": [
      "one-dark-ui",
      "an-old-hope-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
an-old-hope-syntax, v0.5.0
ex-mode, v0.8.0
file-icons, v1.6.14
paner, v0.1.14
pigments, v0.23.0
save-session, v0.15.7
swackets, v0.10.0
vim-mode, v0.64.0
vim-mode-visual-block, v0.2.15
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by shemerey** [comment]
same issue for me

[Enter steps to reproduce below:]
1. split vertical
2. execute panner:very-right

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [paner](https://github.com/t9md/atom-paner) package, v0.1.14

### Stack Trace

Uncaught TypeError: Cannot read property 'activeItem' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:54

TypeError: Cannot read property 'activeItem' of undefined
    at new Pane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:54:31)
    at Object.module.exports.moveToVery (/Users/zork/.atom/packages/paner/lib/main.coffee:163:19)
    at atom-workspace.subscriptions.add.atom.commands.add.paner:very-top (/Users/zork/.atom/packages/paner/lib/main.coffee:54:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:28.2.0 blur (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:28.1.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
  6x -0:28.1.0 blur (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:19.3.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
  5x -0:19.3.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:18.5.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
  5x -0:18.5.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:14.8.0 tree-view:toggle (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -0:14.8.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  4x -0:13.2.0 paner:maximize (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:08.8.0 pane:show-previous-item (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  3x -0:08.8.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:08.4.0 pane:show-next-item (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  3x -0:08.4.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:03.3.0 paner:very-top (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:03.3.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "about",
      "archive-view",
      "autosave",
      "welcome",
      "expose",
      "linter-rubocop",
      "vim-mode",
      "vim-surround",
      "gutter-shadow",
      "atom-beautify"
    ],
    "packagesWithKeymapsDisabled": [
      "tool-bar",
      "circle-ci",
      "ruby-syntax-replacer",
      "emmet",
      "merge-conflicts",
      "dash",
      "color-picker",
      "styleguide",
      "project-manager",
      "linter"
    ],
    "projectHome": "/Users/zork/Projects"
  }
}
```

### Installed Packages

``` coffee
# User
aligner, v0.19.1
aligner-css, v1.2.0
aligner-ruby, v1.4.0
aligner-scss, v1.1.0
color-picker, v2.1.1
docblockr, v0.7.3
editorconfig, v1.2.4
emmet, v2.4.2
esc2, v0.0.0
file-icons, v1.6.18
imdone-atom, v1.3.27
language-docker, v1.1.6
last-cursor-position, v0.9.0
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-docker, v0.1.2
linter-erb, v1.0.2
linter-jscs, v3.4.8
linter-jshint, v2.0.2
linter-sass-lint, v1.1.2
paner, v0.1.14
project-manager, v2.7.6
project-plus, v0.7.0
react, v0.14.1
ruby-syntax-replacer, v0.5.1
symbol-gen, v1.0.0
synced-sidebar, v0.4.3
tool-bar, v0.3.0
vim-mode-plus, v0.23.0
vim-mode-plus-subword-movement, v0.2.2
vim-mode-visual-block, v0.2.15

# Dev
No dev packages
```

**Comment by t9md** [comment]
Sorry everyone, I'm currently not maintaining this package.
So  `move-very-*` action no longer work from when Atom's API change.
I want to recover feature since I want to use `ctrl-w H,J,K,L` but need investigation and free time.

**Comment by c10b10** [comment]
Is there any alternative that you recommend?

**Comment by t9md** [comment]
No. AFAIK there is no package which provides `ctrl-w H,J,K,L`.

**Comment by t9md** [comment]
Fixed and published again, latest version work properly again.
